Finished Tag API calls
Bonni535/e24-rare-meta-server pull request #29
Opened 2024-03-14 00:27 UTC by ctucker0113

2024-03-14 00:28 UTC, Bonni535 approved these changes

2024-03-14 22:50 UTC, GregM1992 commented on API/TagAPI.cs
the error for the tag update needs to be changed to "tag not found"

2024-03-14 22:52 UTC, GregM1992 requested changes
the error for Update Tag needs to be changed to "Tag not found"

2024-03-15 16:58 UTC, GregM1992 approved these changes
lgtm

2024-03-15 16:58 UTC, merged